In [2]:
import tensorflow as tf

In [21]:
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

## Initialization of tensors

In [3]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [4]:
x = tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [5]:
x = tf.constant([1,2,3,4,5,6])
x

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [6]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [7]:
x = tf.zeros((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [8]:
x = tf.eye(3)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [9]:
x = tf.random.normal((3,3), mean=0,stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.5241879 , -1.2776138 ,  2.24117   ],
       [ 1.0522685 , -0.40040317,  0.96755916],
       [-1.1489316 , -0.62379205, -0.6292939 ]], dtype=float32)>

In [10]:
x = tf.random.uniform((3,3), minval=0,maxval=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.954597  , 0.3167373 , 0.48462892],
       [0.19490206, 0.8956108 , 0.13572836],
       [0.3306197 , 0.97697055, 0.1748749 ]], dtype=float32)>

In [11]:
x = tf.range(start=1,limit=10,delta=2) #delta = step
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [12]:
x = tf.cast(x,dtype=tf.float64)
# tf.float (16,32,64), tf.int (8,16,32,64), tf.bool
x

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

## Mathematical Operations

In [13]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y)
z = x+y

z = tf.subtract(x,y)
z = x - y

z = tf.divide(x,y)
z = x / y

z = tf.multiply(x,y)
z = x * y

z = x**2

z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [14]:
x = tf.random.normal((2,3),dtype=tf.float32)
x = tf.random.normal((3,4),dtype=tf.float32)
z = tf.matmul(x,y)
# z = x @ y

z

InvalidArgumentError: cannot compute _MklMatMul as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:MatMul] name: 

## Indexing Tensors

In [ ]:
x = tf.constant([0,1,1,2,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

In [ ]:
indices = tf.constant([0,3])
# x_ind = tf.gather(x,indices)

x = tf.constant([[1,2],[3,4],[5,6]])
print(x[0,:])
print(x[0:2,:])

## Reshaping

In [20]:
x = tf.range(9)

x = tf.reshape(x,(3,3))

x = tf.transpose(x)
print(x)


tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
